USE [master]
GO

/****** Object:  Database [PPC]    Script Date: 06/02/2016 18:39:14 ******/
CREATE DATABASE [PPC] 

ALTER DATABASE [PPC] SET COMPATIBILITY_LEVEL = 120
GO

ALTER DATABASE [PPC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PPC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PPC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PPC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PPC] SET ARITHABORT OFF 
GO

ALTER DATABASE [PPC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PPC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PPC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PPC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PPC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PPC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PPC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PPC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PPC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PPC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PPC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PPC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PPC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PPC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PPC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PPC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PPC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PPC] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PPC] SET  MULTI_USER 
GO

ALTER DATABASE [PPC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PPC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PPC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PPC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PPC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PPC] SET  READ_WRITE 
GO


