USE [PPC]
GO
SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Tree](
	[TreeUid] [uniqueidentifier] NOT NULL DEFAULT (newsequentialid()),
	[Type] [varchar](100) NOT NULL,
	[Depth] [int] NOT NULL,
	[Splitsize] [int] NOT NULL,
	[NumAttrVertex] [int] NOT NULL,
	[NumAttrEdge] [int] NOT NULL,
 CONSTRAINT [Tree_pk] PRIMARY KEY NONCLUSTERED 
(
	[TreeUid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
/****** Object:  Index [ClusteredIndex-Type]    Script Date: 06/02/2016 18:42:51 ******/
CREATE UNIQUE CLUSTERED INDEX [ClusteredIndex-Type] ON [dbo].[Tree]
(
	[Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Vertex](
	[VertexUid] [uniqueidentifier] NOT NULL DEFAULT (newsequentialid()),
	[Name] [varchar](100) NULL,
	[Tree] [varchar](100) NOT NULL,
	[Indice] [int] NOT NULL,
 CONSTRAINT [Vertex_pk] PRIMARY KEY NONCLUSTERED 
(
	[VertexUid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Vertex]  WITH CHECK ADD  CONSTRAINT [FK_Vertex_Tree] FOREIGN KEY([Tree])
REFERENCES [dbo].[Tree] ([Type])
GO

ALTER TABLE [dbo].[Vertex] CHECK CONSTRAINT [FK_Vertex_Tree]
GO

CREATE UNIQUE CLUSTERED INDEX [ClusteredIndex-TreeIndice] ON [dbo].[Vertex]
(
	[Tree] ASC,
	[Indice] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Edge](
	[EdgeUid] [uniqueidentifier] NOT NULL DEFAULT (newsequentialid()),
	[Indice] [int] NOT NULL,
	[Tree] [varchar](100) NOT NULL,
 CONSTRAINT [Edge_pk] PRIMARY KEY NONCLUSTERED 
(
	[EdgeUid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Edge]  WITH CHECK ADD  CONSTRAINT [FK_Edge_Tree] FOREIGN KEY([Tree])
REFERENCES [dbo].[Tree] ([Type])
GO

ALTER TABLE [dbo].[Edge] CHECK CONSTRAINT [FK_Edge_Tree]
GO
CREATE UNIQUE CLUSTERED INDEX [ClusteredIndex-20160130-152522] ON [dbo].[Edge]
(
	[Indice] ASC,
	[Tree] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AttrDef](
	[AttrDefUid] [uniqueidentifier] NOT NULL DEFAULT (newsequentialid()),
	[Name] [varchar](50) NOT NULL UNIQUE,
 CONSTRAINT [PK_AttrDef] PRIMARY KEY CLUSTERED 
(
	[AttrDefUid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AttrVertexUsage](
	[AttrUsageUid] [uniqueidentifier] NOT NULL DEFAULT (newsequentialid()),
	[ObjectVertexUid] [uniqueidentifier] NOT NULL,
	[AttrDefVertexUid] [uniqueidentifier] NULL,
	[Value] [varchar](1000) NULL,
 CONSTRAINT [PK_AttrVertexUsage] PRIMARY KEY NONCLUSTERED 
(
	[AttrUsageUid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[AttrVertexUsage]  WITH CHECK ADD  CONSTRAINT [FK_AttrVertexUsage_AttrDef] FOREIGN KEY([AttrDefVertexUid])
REFERENCES [dbo].[AttrDef] ([AttrDefUid])
GO

ALTER TABLE [dbo].[AttrVertexUsage] CHECK CONSTRAINT [FK_AttrVertexUsage_AttrDef]
GO

ALTER TABLE [dbo].[AttrVertexUsage]  WITH CHECK ADD  CONSTRAINT [ObjectVertexUid_to_Vertex] FOREIGN KEY([ObjectVertexUid])
REFERENCES [dbo].[Vertex] ([VertexUid])
GO

ALTER TABLE [dbo].[AttrVertexUsage] CHECK CONSTRAINT [ObjectVertexUid_to_Vertex]
GO

CREATE CLUSTERED INDEX [ClusteredIndex-VertexAttr] ON [dbo].[AttrVertexUsage]
(
	[ObjectVertexUid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AttrEdgeUsage](
	[AttrUsageUid] [uniqueidentifier] NOT NULL DEFAULT (newsequentialid()),
	[ObjectEdgeUid] [uniqueidentifier] NOT NULL,
	[AttrDefEdgeUid] [uniqueidentifier] NULL,
	[Value] [varchar](1000) NULL,
 CONSTRAINT [PK_AttrEdgeUsage] PRIMARY KEY NONCLUSTERED 
(
	[AttrUsageUid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[AttrEdgeUsage]  WITH CHECK ADD  CONSTRAINT [FK_AttrEdgeUsage_AttrDef] FOREIGN KEY([AttrDefEdgeUid])
REFERENCES [dbo].[AttrDef] ([AttrDefUid])
GO

ALTER TABLE [dbo].[AttrEdgeUsage] CHECK CONSTRAINT [FK_AttrEdgeUsage_AttrDef]
GO

ALTER TABLE [dbo].[AttrEdgeUsage]  WITH CHECK ADD  CONSTRAINT [ObjectEdgeUid_to_Edge] FOREIGN KEY([ObjectEdgeUid])
REFERENCES [dbo].[Edge] ([EdgeUid])
GO

ALTER TABLE [dbo].[AttrEdgeUsage] CHECK CONSTRAINT [ObjectEdgeUid_to_Edge]
GO

CREATE CLUSTERED INDEX [ClusteredIndex-EdgeAttr] ON [dbo].[AttrEdgeUsage]
(
	[ObjectEdgeUid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO